# Cloudflare Tunnel 配置文件示例
# 
# 使用方法：
# 1. 替换 <your-tunnel-id> 为你的实际 Tunnel ID
# 2. 替换 <your-credentials-file> 为你的凭证文件路径
# 3. 运行: cloudflared tunnel --config CLOUDFLARE_TUNNEL_CONFIG.yml run

# Tunnel配置
tunnel: <your-tunnel-id>
credentials-file: <your-credentials-file>

# 入口规则配置
ingress:
  # 管理后台前端 (端口5173)
  - hostname: admin.jianzhile.vip
    service: http://localhost:5173
    originRequest:
      # 保持连接
      noTLSVerify: false
      # HTTP/2支持
      http2Origin: true
  
  # 后端API (端口3000)  
  - hostname: api.jianzhile.vip
    service: http://localhost:3000
    originRequest:
      noTLSVerify: false
      http2Origin: true
      # 长连接支持（用于WebSocket等）
      connectTimeout: 30s
      keepAliveConnections: 100
  
  # 默认规则（必需，处理所有未匹配的请求）
  - service: http_status:404

# 日志配置
logDirectory: /var/log/cloudflared
loglevel: info

# 连接配置
# retries: 3
# grace-period: 30s
